# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

    - name: zip file
      run: zip -r CI.zip ./app.js ./scripts ./appspec.yml ./package.json ./package-lock.json

    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./CI.zip s3://my-githubactionbucket/deploy/

    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
       --application-name my-codedeploy-app \
       --deployment-config-name CodeDeployDefault.OneAtATime \
       --deployment-group-name my-codedeploy-deployment-group \
       --s3-location bucket=my-githubactionbucket,bundleType=zip,key=deploy/CI.zip
